# Generated by Django 5.2.12 on 2026-04-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='original_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll'),
        ),
    ]
