# Generated by Django 5.2.12 on 2026-04-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_original_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='owner',
        ),
    ]
