# Generated by Django 5.2.12 on 2026-04-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxpoll',
            name='owner',
        ),
    ]
